name: dart_web
description: A web server built using the shelf package.
version: 0.0.1
author: Benjamin Thong <benjaminthong@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  logging: ^0.11.3+1
  shelf: ^0.6.0
  shelf_auth:
    git:
      url: https://bitbucket.org/BenjaminThong/shelf_auth.git
      ref: jaguar_jwt
  shelf_cors: ^0.2.1
  shelf_exception_handler: ^0.1.0
  shelf_route: 0.14.3


#dev_dependencies:
#  test: ^0.12.0